"""empty message

Revision ID: 4f8d2dd14569
Revises: 
Create Date: 2021-11-04 19:55:39.714352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8d2dd14569'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pokemon_name', table_name='pokemon')
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.create_index('ix_pokemon_name', 'pokemon', ['name'], unique=False)
    # ### end Alembic commands ###
