"""empty message

Revision ID: 9400b77fb0a8
Revises: 4f8d2dd14569
Create Date: 2021-11-04 21:29:43.696404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9400b77fb0a8'
down_revision = '4f8d2dd14569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pokemon_name', table_name='pokemon')
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.create_index('ix_pokemon_name', 'pokemon', ['name'], unique=False)
    # ### end Alembic commands ###
